// <auto-generated />
using System;
using Domio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Domio.Infrastructure.Persistence.Migrations;

[DbContext(typeof(DomioDbContext))]
[Migration("20260911115500_AddHouseholdInvoices")]
partial class AddHouseholdInvoices
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11");

        BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }

    internal static void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("Domio.Domain.Audit.AuditLog", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<string>("ActorId").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("CorrelationId").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("Description").HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<string>("EntityId").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("EventType").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("NewValuesJson").HasColumnType("TEXT");
            b.Property<string>("OldValuesJson").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("CorrelationId");
            b.HasIndex("CreatedAtUtc");
            b.HasIndex("EventType");
            b.ToTable("AuditLogs");
        });

        modelBuilder.Entity("Domio.Domain.Common.DatabaseMetadataRecord", b =>
        {
            b.Property<int>("Id").ValueGeneratedNever().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("InstanceId").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("DatabaseMetadata");
        });

        modelBuilder.Entity("Domio.Domain.Common.SchemaVersionRecord", b =>
        {
            b.Property<int>("Id").ValueGeneratedNever().HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.Property<int>("Version").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.ToTable("SchemaVersions");
            b.HasData(new
            {
                Id = 1,
                UpdatedAtUtc = new DateTime(
                    2026, 9, 11, 11, 55, 0, DateTimeKind.Utc),
                Version = 15
            });
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.Household", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("CreatedByUserId").HasColumnType("TEXT");
            b.Property<string>("CurrencyCode").IsRequired().HasMaxLength(3).HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("IsActive");
            b.ToTable("Households");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdAccount", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<string>("AccountTypeCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime?>("ArchivedAtUtc").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("CurrencyCode").IsRequired().HasMaxLength(3).HasColumnType("TEXT");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("HouseholdId");
            b.HasIndex("HouseholdId", "IsActive");
            b.ToTable("HouseholdAccounts");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdEntry", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<Guid>("AccountId").HasColumnType("TEXT");
            b.Property<long>("AmountMinor").HasColumnType("INTEGER");
            b.Property<string>("CategoryCode").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<Guid?>("CorrectsEntryId").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("CreatedByUserId").HasColumnType("TEXT");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("EntryTypeCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<DateTime>("OccurredAtUtc").HasColumnType("TEXT");
            b.Property<string>("SourceId").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("SourceType").HasMaxLength(100).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("AccountId");
            b.HasIndex("CategoryCode");
            b.HasIndex("CorrectsEntryId");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("HouseholdId");
            b.HasIndex("HouseholdId", "OccurredAtUtc");
            b.HasIndex("SourceType", "SourceId");
            b.ToTable("HouseholdEntries");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdMember", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<DateTime>("JoinedAtUtc").HasColumnType("TEXT");
            b.Property<DateTime?>("LeftAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("PersonId").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("HouseholdId");
            b.HasIndex("PersonId");
            b.HasIndex("HouseholdId", "PersonId").IsUnique();
            b.ToTable("HouseholdMembers");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdContributionObligation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<long>("AmountMinor").HasColumnType("INTEGER");
            b.Property<Guid>("ContributionRuleId").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<DateTime>("DueDateUtc").HasColumnType("TEXT");
            b.Property<long?>("FixedAmountMinorSnapshot").HasColumnType("INTEGER");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdMemberId").HasColumnType("TEXT");
            b.Property<Guid?>("IncomeOccurrenceId").HasColumnType("TEXT");
            b.Property<Guid?>("IncomeRuleId").HasColumnType("TEXT");
            b.Property<string>("ModeCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<long>("PaidAmountMinor").HasColumnType("INTEGER");
            b.Property<int?>("PercentageBasisPointsSnapshot").HasColumnType("INTEGER");
            b.Property<string>("PeriodKey").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
            b.Property<long?>("PlannedIncomeAmountMinor").HasColumnType("INTEGER");
            b.Property<string>("StatusCode").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
            b.Property<Guid>("TargetHouseholdAccountId").HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("DueDateUtc");
            b.HasIndex("HouseholdId");
            b.HasIndex("HouseholdMemberId");
            b.HasIndex("IncomeOccurrenceId");
            b.HasIndex("IncomeRuleId");
            b.HasIndex("TargetHouseholdAccountId");
            b.HasIndex("ContributionRuleId", "PeriodKey").IsUnique();
            b.ToTable("HouseholdContributionObligations");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdContributionRule", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("CreatedByUserId").HasColumnType("TEXT");
            b.Property<int>("DueOffsetDays").HasColumnType("INTEGER");
            b.Property<long?>("FixedAmountMinor").HasColumnType("INTEGER");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdMemberId").HasColumnType("TEXT");
            b.Property<Guid?>("IncomeRuleId").HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<string>("ModeCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<int?>("PercentageBasisPoints").HasColumnType("INTEGER");
            b.Property<int>("ReminderDays").HasColumnType("INTEGER");
            b.Property<Guid>("TargetHouseholdAccountId").HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.Property<DateTime>("ValidFromUtc").HasColumnType("TEXT");
            b.Property<DateTime?>("ValidToUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("HouseholdId");
            b.HasIndex("HouseholdMemberId");
            b.HasIndex("IncomeRuleId");
            b.HasIndex("TargetHouseholdAccountId");
            b.HasIndex("HouseholdId", "IsActive");
            b.ToTable("HouseholdContributionRules");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdContributionPaymentRequest", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<long>("AmountMinor").HasColumnType("INTEGER");
            b.Property<Guid?>("HouseholdEntryId").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdMemberId").HasColumnType("TEXT");
            b.Property<Guid>("ObligationId").HasColumnType("TEXT");
            b.Property<Guid?>("PersonalTransactionId").HasColumnType("TEXT");
            b.Property<string>("ReviewNote").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<DateTime?>("ReviewedAtUtc").HasColumnType("TEXT");
            b.Property<Guid?>("ReviewedByUserId").HasColumnType("TEXT");
            b.Property<Guid>("SourcePersonalAccountId").HasColumnType("TEXT");
            b.Property<string>("StatusCode").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
            b.Property<DateTime>("SubmittedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("SubmittedByUserId").HasColumnType("TEXT");
            b.Property<Guid>("TargetHouseholdAccountId").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("HouseholdEntryId").IsUnique();
            b.HasIndex("HouseholdId");
            b.HasIndex("HouseholdMemberId");
            b.HasIndex("ObligationId");
            b.HasIndex("PersonalTransactionId").IsUnique();
            b.HasIndex("ReviewedByUserId");
            b.HasIndex("SourcePersonalAccountId");
            b.HasIndex("StatusCode");
            b.HasIndex("SubmittedAtUtc");
            b.HasIndex("SubmittedByUserId");
            b.HasIndex("TargetHouseholdAccountId");
            b.ToTable("HouseholdContributionPaymentRequests");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdInvoice", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<DateTime?>("CancelledAtUtc").HasColumnType("TEXT");
            b.Property<Guid?>("CancelledByUserId").HasColumnType("TEXT");
            b.Property<string>("CategoryCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("CreatedByUserId").HasColumnType("TEXT");
            b.Property<DateTime>("DueDateUtc").HasColumnType("TEXT");
            b.Property<long>("GrossAmountMinor").HasColumnType("INTEGER");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<string>("InvoiceNumber").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<DateTime>("IssueDateUtc").HasColumnType("TEXT");
            b.Property<string>("StatusCode").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
            b.Property<string>("Supplier").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid?>("UtilityInvoiceId").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("CancelledByUserId");
            b.HasIndex("CategoryCode");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("DueDateUtc");
            b.HasIndex("HouseholdId");
            b.HasIndex("StatusCode");
            b.HasIndex("UtilityInvoiceId");
            b.HasIndex("HouseholdId", "Supplier", "InvoiceNumber").IsUnique();
            b.ToTable("HouseholdInvoices");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdInvoicePayment", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<long>("AmountMinor").HasColumnType("INTEGER");
            b.Property<Guid>("CommandId").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("CreatedByUserId").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdAccountId").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdEntryId").HasColumnType("TEXT");
            b.Property<Guid>("HouseholdId").HasColumnType("TEXT");
            b.Property<Guid>("InvoiceId").HasColumnType("TEXT");
            b.Property<DateTime>("PaidAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("HouseholdAccountId");
            b.HasIndex("HouseholdEntryId").IsUnique();
            b.HasIndex("HouseholdId");
            b.HasIndex("InvoiceId");
            b.HasIndex("PaidAtUtc");
            b.HasIndex("HouseholdId", "CommandId").IsUnique();
            b.ToTable("HouseholdInvoicePayments");
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalFinancialAccount", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<string>("AccountTypeCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime?>("ArchivedAtUtc").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("CurrencyCode").IsRequired().HasMaxLength(3).HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
            b.Property<Guid>("OwnerPersonId").HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("OwnerPersonId");
            b.HasIndex("OwnerPersonId", "IsActive");
            b.ToTable("PersonalFinancialAccounts");
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalFinancialTransaction", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<Guid>("AccountId").HasColumnType("TEXT");
            b.Property<long>("AmountMinor").HasColumnType("INTEGER");
            b.Property<string>("CategoryCode").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<Guid?>("CorrectsTransactionId").HasColumnType("TEXT");
            b.Property<string>("Counterparty").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("CreatedByUserId").HasColumnType("TEXT");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("KindCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("OccurredAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("OwnerPersonId").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("AccountId");
            b.HasIndex("CategoryCode");
            b.HasIndex("CorrectsTransactionId");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("OwnerPersonId");
            b.HasIndex("OwnerPersonId", "OccurredAtUtc");
            b.ToTable("PersonalFinancialTransactions");
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalRecurringOccurrence", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<Guid?>("AccountId").HasColumnType("TEXT");
            b.Property<string>("AccountName").HasMaxLength(120).HasColumnType("TEXT");
            b.Property<long?>("ActualAmountMinor").HasColumnType("INTEGER");
            b.Property<DateTime?>("ActualDateUtc").HasColumnType("TEXT");
            b.Property<Guid?>("ActualTransactionId").HasColumnType("TEXT");
            b.Property<string>("CategoryCode").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("Counterparty").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("CurrencyCode").IsRequired().HasMaxLength(3).HasColumnType("TEXT");
            b.Property<string>("KindCode").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<Guid>("OwnerPersonId").HasColumnType("TEXT");
            b.Property<string>("PeriodKey").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
            b.Property<long>("PlannedAmountMinor").HasColumnType("INTEGER");
            b.Property<DateTime>("PlannedDateUtc").HasColumnType("TEXT");
            b.Property<Guid>("RecurringRuleId").HasColumnType("TEXT");
            b.Property<string>("RuleName").HasMaxLength(160).HasColumnType("TEXT");
            b.Property<string>("StatusCode").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("AccountId");
            b.HasIndex("ActualTransactionId");
            b.HasIndex("OwnerPersonId");
            b.HasIndex("PlannedDateUtc");
            b.HasIndex("RecurringRuleId");
            b.HasIndex("RecurringRuleId", "PeriodKey").IsUnique();
            b.ToTable("PersonalRecurringOccurrences");
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalRecurringRule", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<Guid>("AccountId").HasColumnType("TEXT");
            b.Property<string>("CategoryCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("Counterparty").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<Guid>("CreatedByUserId").HasColumnType("TEXT");
            b.Property<string>("CurrencyCode").IsRequired().HasMaxLength(3).HasColumnType("TEXT");
            b.Property<DateTime?>("EndDateUtc").HasColumnType("TEXT");
            b.Property<string>("FrequencyCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<string>("KindCode").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
            b.Property<Guid>("OwnerPersonId").HasColumnType("TEXT");
            b.Property<long>("PlannedAmountMinor").HasColumnType("INTEGER");
            b.Property<DateTime>("StartDateUtc").HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("AccountId");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("OwnerPersonId");
            b.HasIndex("OwnerPersonId", "IsActive");
            b.ToTable("PersonalRecurringRules");
        });

        modelBuilder.Entity("Domio.Domain.Users.Person", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<DateTime?>("ArchivedAtUtc").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("DisplayName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Email").HasMaxLength(254).HasColumnType("TEXT");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Notes").HasMaxLength(2000).HasColumnType("TEXT");
            b.Property<string>("PersonTypeCode").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("Phone").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("Email");
            b.HasIndex("LastName");
            b.HasIndex("PersonTypeCode");
            b.ToTable("People");
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.Household", b =>
        {
            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdAccount", b =>
        {
            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdEntry", b =>
        {
            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdAccount", null)
                .WithMany()
                .HasForeignKey("AccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdEntry", null)
                .WithMany()
                .HasForeignKey("CorrectsEntryId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdMember", b =>
        {
            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.Users.Person", null)
                .WithMany()
                .HasForeignKey("PersonId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdContributionObligation", b =>
        {
            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdContributionRule", null)
                .WithMany()
                .HasForeignKey("ContributionRuleId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdMember", null)
                .WithMany()
                .HasForeignKey("HouseholdMemberId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.PersonalFinance.PersonalRecurringOccurrence", null)
                .WithMany()
                .HasForeignKey("IncomeOccurrenceId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.PersonalFinance.PersonalRecurringRule", null)
                .WithMany()
                .HasForeignKey("IncomeRuleId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdAccount", null)
                .WithMany()
                .HasForeignKey("TargetHouseholdAccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdContributionRule", b =>
        {
            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdMember", null)
                .WithMany()
                .HasForeignKey("HouseholdMemberId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.PersonalFinance.PersonalRecurringRule", null)
                .WithMany()
                .HasForeignKey("IncomeRuleId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdAccount", null)
                .WithMany()
                .HasForeignKey("TargetHouseholdAccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdContributionPaymentRequest", b =>
        {
            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdEntry", null)
                .WithMany()
                .HasForeignKey("HouseholdEntryId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdMember", null)
                .WithMany()
                .HasForeignKey("HouseholdMemberId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdContributionObligation", null)
                .WithMany()
                .HasForeignKey("ObligationId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.PersonalFinance.PersonalFinancialTransaction", null)
                .WithMany()
                .HasForeignKey("PersonalTransactionId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("ReviewedByUserId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.PersonalFinance.PersonalFinancialAccount", null)
                .WithMany()
                .HasForeignKey("SourcePersonalAccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("SubmittedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdAccount", null)
                .WithMany()
                .HasForeignKey("TargetHouseholdAccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdInvoice", b =>
        {
            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CancelledByUserId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.HouseholdFinance.HouseholdInvoicePayment", b =>
        {
            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdAccount", null)
                .WithMany()
                .HasForeignKey("HouseholdAccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdEntry", null)
                .WithMany()
                .HasForeignKey("HouseholdEntryId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.Household", null)
                .WithMany()
                .HasForeignKey("HouseholdId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.HouseholdFinance.HouseholdInvoice", null)
                .WithMany()
                .HasForeignKey("InvoiceId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalFinancialAccount", b =>
        {
            b.HasOne("Domio.Domain.Users.Person", null)
                .WithMany()
                .HasForeignKey("OwnerPersonId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalFinancialTransaction", b =>
        {
            b.HasOne("Domio.Domain.PersonalFinance.PersonalFinancialAccount", null)
                .WithMany()
                .HasForeignKey("AccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.PersonalFinance.PersonalFinancialTransaction", null)
                .WithMany()
                .HasForeignKey("CorrectsTransactionId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.Users.Person", null)
                .WithMany()
                .HasForeignKey("OwnerPersonId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalRecurringOccurrence", b =>
        {
            b.HasOne("Domio.Domain.PersonalFinance.PersonalFinancialAccount", null)
                .WithMany()
                .HasForeignKey("AccountId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.PersonalFinance.PersonalFinancialTransaction", null)
                .WithMany()
                .HasForeignKey("ActualTransactionId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("Domio.Domain.Users.Person", null)
                .WithMany()
                .HasForeignKey("OwnerPersonId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.PersonalFinance.PersonalRecurringRule", null)
                .WithMany()
                .HasForeignKey("RecurringRuleId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.PersonalFinance.PersonalRecurringRule", b =>
        {
            b.HasOne("Domio.Domain.PersonalFinance.PersonalFinancialAccount", null)
                .WithMany()
                .HasForeignKey("AccountId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.Users.UserAccount", null)
                .WithMany()
                .HasForeignKey("CreatedByUserId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.Users.Person", null)
                .WithMany()
                .HasForeignKey("OwnerPersonId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.Users.PersonProfile", b =>
        {
            b.Property<Guid>("PersonId").HasColumnType("TEXT");
            b.Property<DateTime?>("BirthDate").HasColumnType("TEXT");
            b.Property<string>("CorrespondenceBuildingNumber").HasMaxLength(30).HasColumnType("TEXT");
            b.Property<string>("CorrespondenceCity").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("CorrespondenceCountry").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("CorrespondenceNotes").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("CorrespondencePostalCode").HasMaxLength(20).HasColumnType("TEXT");
            b.Property<string>("CorrespondenceRegion").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("CorrespondenceStreet").HasMaxLength(150).HasColumnType("TEXT");
            b.Property<string>("CorrespondenceUnitNumber").HasMaxLength(30).HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("EmergencyContactEmail").HasMaxLength(254).HasColumnType("TEXT");
            b.Property<string>("EmergencyContactFirstName").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("EmergencyContactLastName").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("EmergencyContactNotes").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("EmergencyContactPhone").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("EmergencyContactRelation").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<DateTime?>("IdentityDocumentExpiresOn").HasColumnType("TEXT");
            b.Property<DateTime?>("IdentityDocumentIssuedOn").HasColumnType("TEXT");
            b.Property<string>("IdentityDocumentIssuingCountry").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("IdentityDocumentNumber").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("IdentityDocumentTypeCode").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("Nationality").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Pesel").HasMaxLength(11).HasColumnType("TEXT");
            b.Property<string>("PreferredContactMethodCode").HasMaxLength(50).HasColumnType("TEXT");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("PersonId");
            b.HasIndex("Pesel").IsUnique();
            b.ToTable("PersonProfiles");
        });

        modelBuilder.Entity("Domio.Domain.Users.RoleDefinition", b =>
        {
            b.Property<int>("Id").ValueGeneratedNever().HasColumnType("INTEGER");
            b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
            b.Property<string>("DescriptionPl").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<bool>("IsSystem").HasColumnType("INTEGER");
            b.Property<string>("NamePl").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("PermissionConfigurationJson").HasMaxLength(16000).HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("RoleDefinitions");

            b.HasData(
                new
                {
                    Id = 1,
                    Code = "Administrator",
                    DescriptionPl = "Pełne zarządzanie Domio: użytkownicy, konfiguracja, finanse gospodarstwa, umowy, media i rozliczenia.",
                    IsSystem = true,
                    NamePl = "Administrator"
                },
                new
                {
                    Id = 2,
                    Code = "HouseholdMember",
                    DescriptionPl = "Członek gospodarstwa domowego. Korzysta z funkcji domowych oraz własnych finansów zgodnie z nadanymi uprawnieniami.",
                    IsSystem = true,
                    NamePl = "Domownik"
                },
                new
                {
                    Id = 3,
                    Code = "Tenant",
                    DescriptionPl = "Osoba objęta najmem. Dostęp do własnej umowy, rozliczeń, należności i płatności udostępnionych przez system.",
                    IsSystem = true,
                    NamePl = "Lokator"
                },
                new
                {
                    Id = 4,
                    Code = "Guest",
                    DescriptionPl = "Ograniczony dostęp do wybranych informacji i funkcji bez uprawnień administracyjnych.",
                    IsSystem = true,
                    NamePl = "Gość"
                },
                new
                {
                    Id = 5,
                    Code = "Child",
                    DescriptionPl = "Ograniczony profil członka gospodarstwa przeznaczony dla dziecka; zakres dostępu kontroluje administrator.",
                    IsSystem = true,
                    NamePl = "Dziecko"
                });
        });

        modelBuilder.Entity("Domio.Domain.Users.UserAccount", b =>
        {
            b.Property<Guid>("Id").HasColumnType("TEXT");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
            b.Property<string>("Email").HasMaxLength(254).HasColumnType("TEXT");
            b.Property<int>("FailedLoginAttempts").HasColumnType("INTEGER");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<DateTime?>("LastLoginAtUtc").HasColumnType("TEXT");
            b.Property<DateTime?>("LockoutEndUtc").HasColumnType("TEXT");
            b.Property<string>("LoginName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("NormalizedEmail").HasMaxLength(254).HasColumnType("TEXT");
            b.Property<string>("NormalizedLoginName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<DateTime?>("PasswordChangedAtUtc").HasColumnType("TEXT");
            b.Property<string>("PasswordHash").HasMaxLength(512).HasColumnType("TEXT");
            b.Property<Guid>("PersonId").HasColumnType("TEXT");
            b.Property<int>("RoleDefinitionId").HasColumnType("INTEGER");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").IsUnique();
            b.HasIndex("NormalizedLoginName").IsUnique();
            b.HasIndex("PersonId").IsUnique();
            b.HasIndex("RoleDefinitionId");
            b.ToTable("UserAccounts");
        });

        modelBuilder.Entity("Domio.Domain.Users.PersonProfile", b =>
        {
            b.HasOne("Domio.Domain.Users.Person", null)
                .WithOne()
                .HasForeignKey("Domio.Domain.Users.PersonProfile", "PersonId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Domio.Domain.Users.UserAccount", b =>
        {
            b.HasOne("Domio.Domain.Users.Person", null)
                .WithOne()
                .HasForeignKey("Domio.Domain.Users.UserAccount", "PersonId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Domio.Domain.Users.RoleDefinition", null)
                .WithMany()
                .HasForeignKey("RoleDefinitionId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });
    }
}
