// <auto-generated />
using System;
using Domio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Domio.Infrastructure.Persistence.Migrations;

[DbContext(typeof(DomioDbContext))]
[Migration("20260908124300_AddAuditAndDiagnostics")]
partial class AddAuditAndDiagnostics
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("Domio.Domain.Audit.AuditLog", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("TEXT");

            b.Property<string>("ActorId")
                .HasMaxLength(200)
                .HasColumnType("TEXT");

            b.Property<string>("CorrelationId")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .HasMaxLength(1000)
                .HasColumnType("TEXT");

            b.Property<string>("EntityId")
                .HasMaxLength(200)
                .HasColumnType("TEXT");

            b.Property<string>("EntityType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("TEXT");

            b.Property<string>("EventType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("TEXT");

            b.Property<string>("NewValuesJson")
                .HasColumnType("TEXT");

            b.Property<string>("OldValuesJson")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("CorrelationId");

            b.HasIndex("CreatedAtUtc");

            b.HasIndex("EventType");

            b.ToTable("AuditLogs");
        });

        modelBuilder.Entity("Domio.Domain.Common.DatabaseMetadataRecord", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedNever()
                .HasColumnType("INTEGER");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("TEXT");

            b.Property<string>("InstanceId")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("DatabaseMetadata");
        });

        modelBuilder.Entity("Domio.Domain.Common.SchemaVersionRecord", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedNever()
                .HasColumnType("INTEGER");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasColumnType("TEXT");

            b.Property<int>("Version")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.ToTable("SchemaVersions");

            b.HasData(
                new
                {
                    Id = 1,
                    UpdatedAtUtc = new DateTime(
                        2026, 9, 8, 12, 43, 0, DateTimeKind.Utc),
                    Version = 2
                });
        });
#pragma warning restore 612, 618
    }
}
