// <auto-generated />
using System;
using Domio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domio.Infrastructure.Persistence.Migrations;

[DbContext(typeof(DomioDbContext))]
partial class DomioDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("Domio.Domain.Common.SchemaVersionRecord", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedNever()
                .HasColumnType("INTEGER");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasColumnType("TEXT");

            b.Property<int>("Version")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.ToTable("SchemaVersions");

            b.HasData(
                new
                {
                    Id = 1,
                    UpdatedAtUtc = new DateTime(
                        2026, 9, 8, 0, 0, 0, DateTimeKind.Utc),
                    Version = 1
                });
        });
#pragma warning restore 612, 618
    }
}
